# Generated by Django 5.0.4 on 2024-04-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('delivered', models.BooleanField(default=False, verbose_name='Доставлен')),
                ('guest_name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('guest_lastname', models.CharField(max_length=255, null=True, verbose_name='Фамилия')),
                ('guest_phone', models.CharField(max_length=255, null=True, verbose_name='Номер телефона')),
                ('items', models.ManyToManyField(to='mainapp.parts', verbose_name='Заказанные запчасти')),
            ],
        ),
    ]
